components:
  parameters:
    deviceId:
      description: ID of the device to return
      explode: false
      in: path
      name: deviceId
      required: true
      schema:
        format: int64
        type: integer
      style: simple
  schemas:
    ApiResponse:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        type:
          type: string
      type: object
    Category:
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
    Device:
      example:
        category:
          id: 10
          name: phone
        id: 1
        manufacturer: Apple Inc.
        model: QQ123Q
        name: IPhone 11
        price: $2000
        status: available
        tags:
        - id: 1
          name: dual-camera
      properties:
        category:
          $ref: '#/components/schemas/Category'
        id:
          format: int64
          type: integer
        manufacturer:
          type: string
        model:
          type: string
        name:
          type: string
        price:
          type: string
        status:
          description: device status in the store
          enum:
          - available
          - out-of-stock
          type: string
        tags:
          items:
            $ref: '#/components/schemas/Tag'
          type: array
      required:
      - name
      - photoUrls
    DeviceList:
      example:
        count: 3
        list:
        - category:
            id: 10
            name: phone
          id: 1
          manufacturer: Apple Inc.
          model: QQ123Q
          name: IPhone 11
          price: $2000
          status: available
          tags:
          - id: 1
            name: dual-camera
        - category:
            id: 10
            name: phone
          id: 3
          manufacturer: Huawei Inc.
          model: QQT23Q
          name: Nova 2i
          price: $250
          status: available
          tags:
          - id: 1
            name: dual-camera
        - category:
            id: 10
            name: phone
          id: 12
          manufacturer: Nokia Inc.
          model: WFF123S
          name: Nokia 7
          price: $320
          status: out-of-stock
      properties:
        count:
          format: int64
          type: integer
        list:
          items:
            $ref: '#/components/schemas/Device'
          type: array
    Tag:
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      type: object
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
info:
  contact:
    email: apiteam@mobilepioneer.io
  description: This is the API used for Altronica Inc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://altronica.io/terms/
  title: MobileStore
  version: "1.0"
openapi: 3.0.0
paths:
  /mobile-devices:
    get:
      operationId: getAllDevices
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceList'
          description: Succesfully returned the devices
        "405":
          description: Invalid input
      summary: Get all mobile devices in the store
      tags:
      - devices
    post:
      operationId: addDevice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
        description: Mobile Device object that needs to be added to the store
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
          description: Sucessfully created the device
        "405":
          description: Invalid input
      summary: Add a new mobile device to the store
      tags:
      - devices
  /mobile-devices/{deviceId}:
    delete:
      operationId: deleteDeviceById
      parameters:
      - $ref: '#/components/parameters/deviceId'
      responses:
        "200":
          description: Successfully deleted the device
        "400":
          description: Invalid ID supplied
        "404":
          description: Device not found
      summary: Deletes a device
      tags:
      - devices
    get:
      description: Returns a single mobile device represented by the ID
      operationId: getDeviceById
      parameters:
      - $ref: '#/components/parameters/deviceId'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
          description: successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Device not found
      summary: Find Mobile Device by ID
      tags:
      - devices
    put:
      operationId: updateDeviceById
      parameters:
      - $ref: '#/components/parameters/deviceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
        description: Mobile Device object that needs to be updated in the store
        required: true
      responses:
        "405":
          description: Invalid input
      summary: Updates a Device in the store
      tags:
      - devices
  /mobile-devices/{deviceId}/uploadImage:
    post:
      operationId: uploadFile
      parameters:
      - $ref: '#/components/parameters/deviceId'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
          description: successful operation
      summary: uploads an image to the device
      tags:
      - devices
servers:
- url: https://localhost/mobile-store
tags:
- description: Mobile devices
  externalDocs:
    description: Find out more
    url: http://mobilepioneer.io
  name: devices

